name: Deploying to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd resume-backend
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github-afiqzudinhadi
            git pull
            npm run stop
            npm run start
